refactoring
mashelll/smart-home-2019 pull request #1
Opened 2019-10-10 16:12 UTC by mashelll

2019-10-16 19:58 UTC, iagoshkov requested changes
Исправьте по замечаниям.

2019-10-16 19:58 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/ReadingUtils/SmartHomeReader.java
> +    public SmartHome read() throws IOException;
IOException лучше бы конечно убрать, оставить чистую абстракцию предоставления дома из любого источника, сейчас IOException намекает на то, что дом всегда читается из файла.
А это может зависеть от реализации - завтра захотим хранить дом в БД и никакого IOException уже не будет, будут SQLException.
Все эти детали надо из абстракции убрать, иначе у нас получается leakyAbstraction.
https://en.wikipedia.org/wiki/Leaky_abstraction

2019-10-16 19:58 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent/SensorEventDoor.java
> +    public void performEvent(SmartHome smartHome) {
Здесь нарушен SRP.
Вы делаете две вещи - обновляете состояние дома по событию + запускаете сценарий умного дома.
А в будущем у нас будет появляться необходимость добавлять все больше и больше обработчиков на одни и те же события.
Подумайте как исправить.

2019-10-16 19:58 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent/SensorEventDoor.java
> +    public void performEvent(SmartHome smartHome) {
Hint: возможно не надо обработку событий реализовывать в самом классе события.

2019-10-16 19:58 UTC, iagoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEvent event = SensorEventGenerator.getNextSensorEvent();
А когда мы захотим подключить библиотеку, получающую события из реального дома и датчиков - нам придется менять этот код?
SensorEventGenerator генерирует случайные события и это не должно быть "зашито" здесь.
Нарушены SRP/OCP.
Исправьте.

2019-10-16 19:58 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          while (event != null) {
Сам цикл обработки событий и их диспетчеризации лучше также вынести в другое место.
Иначе SRP нарушен.
Исправьте.

2019-10-16 19:58 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent/SensorEventLight.java
> +    public static void turnAllLightsOff(SmartHome smartHome) {
Почему этот метод в этом классе?
Какой у него cohesion с методом performEvent?
Правильно, нулевой.
Нарушен SRP.
Исправьте.
Мы это все проговаривали на прошлом занятии.

2019-10-22 08:41 UTC, a-ivanov commented
Добавьте в .gitignore и удалите файлы из пулл реквеста в директории target/classes/ru/sbt/mipt/oop. Это байткод, он не является частью исходного кода проекта.

2019-10-22 08:49 UTC, a-ivanov requested changes
В целом хорошо, удалите байткод из репозитория и немного поправьте.

2019-10-22 08:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ReadingUtils/SmartHomeReaderJSON.java
> +        SmartHome smartHome = gson.fromJson(json, SmartHome.class);
Если выше произойдет exception, то тут json=null. gson.fromJson умеет работать с null?

2019-10-22 08:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Executor.java
> +        List<EventHandler> handlers = HandlersConstructor.constructHandlers(smartHome);
Просто совет: вполне можно передавать снаружи и хранить в поле Executor вместо отдельного класса HandlersConstructor.

2019-10-22 08:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent/ActionType.java
> +public interface ActionType {
Просто комментарий: можно все типы держать в одном enum. DoorActionType и LightActionType каждый в отдельности не отличается по использованию от другого, а количество абстракций лучше минимизировать (без потери качества кода).

2019-10-22 08:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome/HomeBuilder.java
> +package ru.sbt.mipt.oop.SmartHome;
В Java принято пакеты называть всеми строчными. Исправьте.

2019-10-22 08:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome/SmartHome.java
> +public class SmartHome implements Actionable{
Поставьте пробел после интерфейса.

2019-11-07 18:13 UTC, merged